jenkinsci/parameterized-trigger-plugin

- src/main/java/hudson/plugins/parameterizedtrigger/BuildInfoExporterAction.java
Replaces #78.
To try it out go to <build-url>/api/json?pretty=true&depth=1 of a build that triggered another build via the parameterized trigger build step. Then you will see something like this:
```json
{
"actions" : [
...,
{
"triggeredBuilds" : [
],
"triggeredProjects" : [
{
"name" : "chain-step-1",
"url" : "http://localhost:8080/job/chain-step-1/",
"color" : "blue"
}
]
}
],
...
}
```
> [FIXED JENKINS-26031] Added export of triggered builds and jobs to XML/JSON API

- pom.xml
- src/main/java/hudson/plugins/parameterizedtrigger/AbstractBuildParameterFactory.java
- src/main/java/hudson/plugins/parameterizedtrigger/BlockableBuildTriggerConfig.java
- src/main/java/hudson/plugins/parameterizedtrigger/BuildTrigger.java
- src/main/java/hudson/plugins/parameterizedtrigger/BuildTriggerConfig.java
- src/main/java/hudson/plugins/parameterizedtrigger/DefaultParameterValuesActionsTransform.java
- src/main/java/hudson/plugins/parameterizedtrigger/ITransformProjectParametersAction.java
- src/main/java/hudson/plugins/parameterizedtrigger/ProjectSpecificParameterValuesActionTransform.java
- src/main/java/hudson/plugins/parameterizedtrigger/ProjectSpecificParametersActionFactory.java
- src/main/java/hudson/plugins/parameterizedtrigger/TriggerBuilder.java
- src/main/resources/hudson/plugins/parameterizedtrigger/BuildTriggerConfig/config.jelly
- src/test/java/hudson/plugins/parameterizedtrigger/test/BuildTriggerConfigTest.java
- src/test/java/hudson/plugins/parameterizedtrigger/test/TriggerBuilderTest.java
Per [JENKINS-26050](https://issues.jenkins-ci.org/browse/JENKINS-26050) this fixes workflow compatibility, and adds unit tests for same.
@reviewbybees
> [JENKINS-26050] Fix Workflow compatibility for Parameterized Trigger

- src/main/java/hudson/plugins/parameterizedtrigger/TriggerBuilder.java
- src/test/java/hudson/plugins/parameterizedtrigger/test/TriggerBuilderTest.java
Builds on top of fix in [PR #90](https://github.com/jenkinsci/parameterized-trigger-plugin/pull/90) but includes tests.  I've manually verified this works correctly from the UI as well. 
@tonyfinn @reviewbybees
> [JENKINS-30040] Logging exception running triggering nonblocking builds

- src/main/resources/hudson/plugins/parameterizedtrigger/BlockableBuildTriggerConfig/config.jelly
- src/test/java/hudson/plugins/parameterizedtrigger/test/FileBuildParameterFactoryTest.java
- src/test/java/hudson/plugins/parameterizedtrigger/test/FileBuildTriggerConfigTest.java
- src/test/java/hudson/plugins/parameterizedtrigger/test/ResultConditionTest.java
Mainly fix unit tests for default encoding on Windows plus some other minor fixes and improvements.
> Miscellaneous minor fixes and improvements

- src/main/java/hudson/plugins/parameterizedtrigger/FileBuildParameters.java
Log a message instead of throwing a NullPointerException if build.getWorkspace() is null.
Are there any tests I could meaningfully extend for this?
> Don't throw an NPE if build.getWorkspace() is null

- src/main/java/hudson/plugins/parameterizedtrigger/BuildTriggerConfig.java
- src/main/java/hudson/plugins/parameterizedtrigger/ParameterizedTriggerUtils.java
- src/test/java/hudson/plugins/parameterizedtrigger/test/BuildTriggerConfigTest.java
Right now user can provide list of project with extra comma. I.e. `"projectA, "`
And verification passes.
But after execution user receives:
```
ERROR: Build aborted. Can't trigger undefined projects. 1 of the below project(s) can't be resolved:
> 
> projectA
Check your configuration!
```
It happens because in `TriggerBuilder.java` we have check like this:
```
// Get the actual defined projects
StringTokenizer tokenizer = new StringTokenizer(config.getProjects(env), ",");
...
if (tokenizer.countTokens() != projectList.size()) {
```
And as result number of tokens are bigger than number of projects (because we skipped empty one before). So, I adjust this check with the most earliest existed check I found.
> Fix extra comma error in list of projects

- src/main/java/hudson/plugins/parameterizedtrigger/TriggerBuilder.java
- src/test/java/hudson/plugins/parameterizedtrigger/test/TriggerBuilderTest.java
NPE happens in rare case:
1) We have X projects
2) We disabled one of them
3) Trigger fired X-1 projects and filled map <projectName, executor>
4) Job was fixed, and we enable this job again
5) Trigger is waiting for all projects (now it's X projects again)
6) It tries to access job that we re-enabled -> it doesn't exist in map => NPE
How it looks like in logs:
```
Waiting for the completion of projectA
projectA #22344 completed. Result was SUCCESS
Waiting for the completion of projectB
ERROR: Build step failed with exception
java.lang.NullPointerException
Build step 'Trigger/call builds on other projects' marked build as failure
```
I failed to create test case for it :( .Because those two lines are too close to each other:
```
ListMultimap<Job, Future<Run>> futures = …
```
> Fix NPE in case of race condition

- src/main/java/hudson/plugins/parameterizedtrigger/BuildTrigger.java
- src/main/java/hudson/plugins/parameterizedtrigger/DynamicBuildAction.java
- src/main/java/hudson/plugins/parameterizedtrigger/DynamicProjectAction.java
- src/main/resources/hudson/plugins/parameterizedtrigger/DynamicBuildAction/summary.groovy
- src/main/resources/hudson/plugins/parameterizedtrigger/DynamicProjectAction/jobMain.groovy
Ability to pass build parameters in the post-build action 'Trigger parameterized build on other projects'.
Like ${bugID}/assembly, which ${bugID} is a string build parameter.
Also, I've added actions to job and build that shows a list of downstream projects that passed with parameters.
> Add an ability to pass build parameters to post build trigger

- pom.xml
- src/test/java/hudson/plugins/parameterizedtrigger/test/BuildTriggerConfigTest.java
- src/test/java/hudson/plugins/parameterizedtrigger/test/CounterBuildParameterFactoryTest.java
- src/test/java/hudson/plugins/parameterizedtrigger/test/CurrentBuildParametersTest.java
- src/test/java/hudson/plugins/parameterizedtrigger/test/DefaultParametersTest.java
- src/test/java/hudson/plugins/parameterizedtrigger/test/FileBuildParameterFactoryTest.java
- src/test/java/hudson/plugins/parameterizedtrigger/test/FileBuildTriggerConfigTest.java
- src/test/java/hudson/plugins/parameterizedtrigger/test/PredefinedPropertiesBuildTriggerConfigTest.java
- src/test/java/hudson/plugins/parameterizedtrigger/test/TriggerBuilderTest.java
With the new changes to the plugin compatibility tester, a few of this plugin's tests fail.  The plugin compat tester tests a plugin against the newest version of it's dependencies as if it's been installed on the newest version of Jenkins.  This led to some failures even though when running tests on the current Jenkins version were no issues.
Currently this depends on the 1.x line of the workflow plugins.  Since there were significant changes with this plugin upon the 2.x release, I updated them and included new plugins that replicate the old functionality.  Also, I bumped the plugin-pom version as well as matirx-auth to get out of the "break-cycles" issue.  I had to bump the jenkins.version to 1.638 for missing pieces for the new workflow plugins.  That's the lowest version that I could …
> plugin compat tester fixes

- src/main/java/hudson/plugins/parameterizedtrigger/BuildTriggerConfig.java
*SECURITY-201* has introduced on this plugin a NPE on this exactly commit https://github.com/jenkinsci/parameterized-trigger-plugin/commit/89a6148414f48430f36d05973a803b0bb581f732
The NPE happens in https://github.com/jenkinsci/parameterized-trigger-plugin/blob/parameterized-trigger-2.35/src/main/java/hudson/plugins/parameterizedtrigger/BuildTrigger.java#L111 due future being null.
* https://issues.jenkins-ci.org/browse/JENKINS-45471
@reviewbybees CC @oleg-nenashev (since afaik you introduced this)
> [JENKINS-45471] Not add null values to the list

- src/main/java/hudson/plugins/parameterizedtrigger/BuildTriggerConfig.java
The change polishes #114 and adds check of another NPE risk in `BuildTriggerConfig#perform3()`. Will add tests later... really...
https://issues.jenkins-ci.org/browse/JENKINS-45471
@reviewbybees @fbelzunc
> [JENKINS-45471] - Generalize handling of scheduling errors and prevent NPEs in perform3()

- src/main/java/hudson/plugins/parameterizedtrigger/BuildTrigger.java
- src/main/java/hudson/plugins/parameterizedtrigger/TriggerBuilder.java
- src/test/java/hudson/plugins/parameterizedtrigger/test/TriggerBuilderTest.java
Continuation from #109. See this PR for previous discussions.
My colleague is on parental leave, but I'll continue the work one this fork. The code has now been rebased against master. A test cases has been added that shows that a downstream project is indeed triggered twice if shouldTriggerBuild() does not return false.
This pull request fixes visualization of plugins like Downstream View Plugin and other issues like JUnit test result aggregation, where a graph of triggered projects is typically traversed.
> TriggerBuilder now implements DependencyDeclarer

- pom.xml
Downstream of https://github.com/jenkinsci/plugin-pom/pull/67.
@reviewbybees
> [JENKINS-41631] Demonstration of POM update

- src/main/java/hudson/plugins/parameterizedtrigger/BlockableBuildTriggerConfig.java
- src/main/java/hudson/plugins/parameterizedtrigger/BuildTrigger.java
- src/main/java/hudson/plugins/parameterizedtrigger/BuildTriggerConfig.java
- src/main/java/hudson/plugins/parameterizedtrigger/TriggerBuilder.java
- src/test/java/hudson/plugins/parameterizedtrigger/test/TriggerBuilderTest.java
This makes it much easier to find the child job while it
is running and not yet finished.
This is implemented with QueueTaskFuture's waitForStart()
method that returns the job once it starts running. The Future
waited on was already an instance of QueueTaskFuture, but
I needed to plumb through the type instead of the Future
interface.
Testing:
* Added checks to a couple of unit tests for the new log lines.
* Ran unit tests.
* Tested plugin on a production jenkins instance.
> [JENKINS-57442]: print link to running job

- src/main/resources/hudson/plugins/parameterizedtrigger/BuildInfoExporterAction/summary.groovy
The innocent looking print() call actually ends up in the Jenkins log
and not in the outputted HTML sent via the browser. To output content
to the webbrowser text() should be used, and is used a few lines later.
This print out causes a lot of pain on our servers as everytime someone loads a build page it spams our system log with debug information, e.g.:
```
INFO: a_upstream #1 main build action completed: SUCCESS
hudson.model.FreeStyleProject@50635a73[a_downstream]Jul 17, 2019 2:08:30 PM hudson.model.Run execute
INFO: a_downstream #1 main build action completed: SUCCESS
hudson.model.FreeStyleProject@50635a73[a_downstream]hudson.model.FreeStyleProject@50635a73[a_downstream]hudson.model.FreeStyleProject@50635a73[a_downstream]hudson.model.FreeStyleProject@50635a73[a_downstream]hudson.model.F …
```
> Removed debug print causing printout in jenkins log

- README.md
- src/main/java/hudson/plugins/parameterizedtrigger/ParameterizedTriggerUtils.java
- src/main/resources/hudson/plugins/parameterizedtrigger/BuildInfoExporterAction/summary.groovy
- src/main/resources/hudson/plugins/parameterizedtrigger/DynamicBuildAction/summary.groovy
- src/main/resources/hudson/plugins/parameterizedtrigger/DynamicProjectAction/jobMain.groovy
- src/main/resources/hudson/plugins/parameterizedtrigger/SubProjectsAction/jobMain.groovy
Set Java property "ptp.disableActionViews" (typically Launch Jenkins
with -Dptp.disableActionViews) to stop the listing of "Sub Projects"
on the build and project main pages. This can be of use when other
plugins are used to render the upstream/downstream flow and there is
reduntant information displayed about the triggered builds.
> Feature: System property ptp.disableActionViews disables summary

- CHANGELOG.md
- README.md
Just a best-effort migration.
The syntax on https://wiki.jenkins.io/display/JENKINS/Parameterized+Trigger+Plugin is pretty complicated, and it looks like some information entries got lost.
> Move the documentation from Wiki to GitHub

- src/main/java/hudson/plugins/parameterizedtrigger/NodeParameters.java
Proposed fix for https://issues.jenkins-ci.org/browse/JENKINS-57472.
If the build machine running the project disconnects while it is running (causing the build to be aborted), then calling `getBuiltOn()` will result in returning _null_ (because this function is asking the Jenkins instance to get the node with the built on label, which no longer exists).  This null incorrectly causes the plugin to build the triggered project on master (potentially with disastrous results).
This PR changes the code snippet to use `getBuiltOnStr()` instead, which returns the node label string.  If _this_ is null or empty string, then it is safe to assume we were built on master; if not, we'll convert the node label string directly into a label and return it, without asking the Jenkins instance to find the …
> [JENKINS-57472] Keep node label even if machine disconnects

- pom.xml
> Use GitHub as a source of documentation on plugins.jenkins.io

- .github/workflows/changelog.yml
Looks like the release drafter is stuck, maybe because of https://github.com/release-drafter/release-drafter/pull/313 which does not seem to be deployed
> Use GitHub actions to generate release drafts

- pom.xml
To be replaced by https://issues.jenkins-ci.org/browse/WEBSITE-658, sooner or later
> Cleanup obsolete maintainer INFO

- .gitignore
- .mvn/extensions.xml
- .mvn/maven.config
- pom.xml
- src/main/java/hudson/plugins/parameterizedtrigger/BuildTriggerConfig.java
- src/test/java/hudson/plugins/parameterizedtrigger/test/BuildTriggerConfigTest.java
To work with https://github.com/jenkinsci/jenkins/pull/4848.
> Compatibility with Spring Security

- README.md
See
https://github.com/jenkins-infra/jenkins.io/issues/3948#issuecomment-724514107
for the background on this pull request; in short, I saw "Subprojects"
in a Jenkins UI and didn't know what it meant. It would be nice if this
was defined in the README for the plugin that adds that UI element. :)
> Add a definition of the term "Subprojects" that appears in Jenkins UI

- src/main/java/hudson/plugins/parameterizedtrigger/BlockingBehaviour.java
When this plugin is used to call another job during the build or pre-scm build stages, and the user chooses to block on the job until it's completed, this plugin sets the parent job status to "SUCCESS", even though there should be no assumption that the success of the child job mandates success of the parent job.
Example:
1. Job A -> enables "Run buildstep before SCM runs" and adds a "Trigger/call builds on other projects" step, to call Job B
2. Job B completes successfully.
3. The parameterized trigger plugin sets the result of Job A to "SUCCESS" even though nothing that's happened so far indicates that Job A is "SUCCESS".
This can cause strange issues in a few cases; for example, the extended e-mail notifier plugin can send e-mails at various stages, including "immediately before the …
> Don't automatically mark the parent job as SUCCESS

- pom.xml
- src/main/resources/hudson/plugins/parameterizedtrigger/BooleanParameters/config.jelly
- src/main/resources/hudson/plugins/parameterizedtrigger/BuildTrigger/config.jelly
- src/main/resources/hudson/plugins/parameterizedtrigger/TriggerBuilder/config.jelly
https://issues.jenkins.io/browse/JENKINS-64502
cc @olamy
> JENKINS-64502 Fix plugin on Jenkins >=2.264

- src/main/java/hudson/plugins/parameterizedtrigger/BinaryFileParameterFactory.java
- src/main/java/hudson/plugins/parameterizedtrigger/BlockableBuildTriggerConfig.java
- src/main/java/hudson/plugins/parameterizedtrigger/BlockingBehaviour.java
- src/main/java/hudson/plugins/parameterizedtrigger/BuildTriggerConfig.java
- src/main/java/hudson/plugins/parameterizedtrigger/TriggerBuilder.java
Should also prevent https://issues.jenkins.io/browse/JENKINS-64502?focusedCommentId=402814&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-402814
Drops the number of spotbugs to 4 from 10
> Fix Null pointer exceptions

- src/test/java/hudson/plugins/parameterizedtrigger/test/BuildTriggerTest.java
Saw a `plugin-compat-tester` failure
```
java.lang.AssertionError: Downstream job should be triggered
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertNotNull(Assert.java:713)
at hudson.plugins.parameterizedtrigger.test.BuildTriggerTest.testParentProjectTrigger(BuildTriggerTest.java:65)
```
Guessing this was a race condition but hard to know since there are no log messages while the test runs:
```
…
0.793 [id=…]	INFO	jenkins.InitReactorRunner$1#onAttained: Completed initialization
4.662 [id=…]	INFO	jenkins.model.Jenkins#cleanUp: Stopping Jenkins
…
```
This patch helps some, though if https://github.com/jenkinsci/jenkins/pull/4345#discussion_r348496722 had been accepted it would have helped more.
> More logging for BuildTriggerTest.testParentProjectTrigger

- pom.xml
- src/test/java/hudson/plugins/parameterizedtrigger/test/BuildTriggerTest.java
There was the possibility of a race condition where the queue was empty but the downstream job not yet added to it, resulting in assertions about the downstream being checked too early and fail.
Show in a CI run under heavy load, not something usual, but this change should remove the possibility
> Fix flakiness in BuildTriggerTest

- pom.xml
Especially because it pulls in a hard dep on `maven-plugin`! (https://github.com/jenkinsci/conditional-buildstep-plugin/pull/27)
Was done correctly in #42 but regressed in #100.
> `conditional-buildstep` dep should be optional

- pom.xml
Use https protocol instead of git protocol because GitHub is deprecating git protocol
> Use https instead of git

- src/test/java/hudson/plugins/parameterizedtrigger/CapturedEnvironmentActionTest.java
- src/test/java/hudson/plugins/parameterizedtrigger/test/BuildTriggerTest.java
https://issues.jenkins.io/browse/JENKINS-68964
Fix flickering BuildTriggerTest#testParentProjectTrigger
Building dependency graph is async process, and from time to time it is not complete when upstream job finished. 
Suggestion is to build graph manually as most of the tests in plugin already do.
> [Flakiness Reduction] rebuild graph manually 

- src/main/resources/index.jelly
Adds missing index.jelly to fix plugin's presentation in plugin manager and plugin site.
https://issues.jenkins.io/browse/JENKINS-68300
- [n/a] Link to relevant pull requests, esp. upstream and downstream changes
- [n/a] Ensure you have provided tests - that demonstrates feature works or fixes the issue
> Add descrption for plugin manager

- pom.xml
- suppressed-spotbug-errors.xml
This plugin will be used the DW2022 Contributing Workshop. In order to keep the focus of trainees, I propose to suppress the spotbugs errors. The compile will not have impressive warnings and the CI job has more chances to run successfully.
Suppressed warnings are stored in the suppressed-spotbug-errors.xml file
> Suppress spotbugs errors

- Jenkinsfile
- Use useContainerAgent instead of useAci in Jenkinsfile
- Use single quoted strings in Jenkinsfile
- Do not test JDK 17 in CI
Java 17 fails tests because it is attempting to serialize mockito objects in a way that Java 17 appears to not allow.  Needs fixes before Java 17 is enabled in CI.
> Disable Java 17 in CI

- pom.xml
- Manage subversion dependency version from bom
- Remove unused workflow-cps exclusion
- Remove unused matrix-auth exclusion
- Remove unused mockito-core exclusion
- Remove unused awaitility exclusion
- Use error_prone_annotations version from bom
- Use commons-lang3 version from bom
- Use spotbugs-annotations version from bom
- Use access-modifier-annotation from parent
Remove dependency declarations and exclusions that are no longer required now that bill of materials is being used.
> Simplify plugin dependency declarations

- src/main/java/hudson/plugins/parameterizedtrigger/BlockingBehaviour.java
- src/main/java/hudson/plugins/parameterizedtrigger/BuildTriggerConfig.java
- src/test/java/hudson/plugins/parameterizedtrigger/test/ParameterizedTriggerPermissionTest.java
JSR-305 was never adopted.  The Jenkins project has switched to Spotbugs annotations and provides them in the parent pom.
> Use spotbugs annotations instead of JSR-305

- src/main/java/hudson/plugins/parameterizedtrigger/ParameterizedTriggerUtils.java
Fix a javadoc warning by removing an empty link.
Confirmed the Javadoc warning was visible before this change and that it is not visible after the change.
> Fix javadoc warning

- pom.xml
The spotbugs configuration in the parent pom will fail on error.  No need to set it in the pom of the plugin.
Confirmed that plugin compilation runs as expected.
> Remove redundant spotbugs setting

- src/main/java/hudson/plugins/parameterizedtrigger/TriggerBuilder.java
- src/test/java/hudson/plugins/parameterizedtrigger/test/TriggerBuilderTest.java
Cancel triggered build on InterruptException
When a triggering project is cancelled by interrupting its Executor thread and a triggered project is waiting in the build queue (via `waitForStart()`) the InterruptedException is not handled.  The tiggered project is properly cancelled, but the triggering project is left in the queue and will eventually run when a slot is available.
Catch InterruptException while waiting for the triggered project to start and cancel the queued run.
Stacktrace with parameterized-trigger-2.44:
```
org.jenkinsci.plugins.postbuildscript.PostBuildScriptException: java.lang.InterruptedException
at org.jenkinsci.plugins.postbuildscript.processor.Processor.processBuildSteps(Processor.java:190)
at org.jenkinsci.plugins.postbuildscript.processor.Processor.processScripts( …
```
> Cancel pending triggered build when parent project is cancelled

- src/main/resources/hudson/plugins/parameterizedtrigger/BuildInfoExporterAction/summary.groovy
This PR fixes https://issues.jenkins.io/browse/JENKINS-71919
`mvn -ntp clean verify` maven command is successful
```[tasklist]
```
> JENKINS-71919 Use modern icon class in subproject page

- .github/dependabot.yml
- pom.xml
892.vd6219fc0a_efb was released 2 years ago.  Over 50% of all installations of the promoted builds plugin are already using 892.vd6219fc0a_efb or newer.  Those users will see no difference from this change, since they are already using 892.vd6219fc0a_efb.
Recent Jenkins versions will display broken icons with older versions of the promoted builds plugin.  Fixed in https://github.com/jenkinsci/promoted-builds-plugin/pull/170 as part of 873.v6149db_d64130.  Upgrading to 892.vd6219fc0a_efb will fix that issue for users.
[Installation statistics](https://stats.jenkins.io/pluginversions//parameterized-trigger.html) show that 892.vd6219fc0a_efb is the second most popular release.  It is second only to the most recent release, 945.v597f5c6a_d3fd.  A step towards eventually upgrading the …
> Bump promoted-builds optional dependency to 892.vd6219fc0a_efb

- src/main/java/hudson/plugins/parameterizedtrigger/TriggerBuilder.java
I keep having log messages such as:
WARNING: [hudson.plugins.parameterizedtrigger.TriggerBuilder perform]
Attempting to use the result of unfinished build <name of job> #1234
The message was introduced in #161 by 06d8f19218 but in #148 / 02ee6ea5, mapBuildResult() was made to return `null` by default (eg on SUCCESS).
The resut is the warning is always triggered when the triggered build succeeds.
Fixes https://phabricator.wikimedia.org/T336782
```[tasklist]
```
> Do not warn when triggered job is a success

- src/main/java/hudson/plugins/parameterizedtrigger/BuildInfoExporterAction.java
- src/main/java/hudson/plugins/parameterizedtrigger/BuildTriggerConfig.java
- src/main/java/hudson/plugins/parameterizedtrigger/ParameterizedTriggerUtils.java
While releasing the most recent version, there were javadoc warnings reported in the build log.  Fix those javadoc warnings.
Confirmed that Javadoc warnings are no longer visible after these changes.
```[tasklist]
```
> Fix javadoc warnings

- CHANGELOG.md
- README.md
- src/main/resources/hudson/plugins/parameterizedtrigger/CounterBuildParameterFactory/help-validationFail.html
- src/main/resources/hudson/plugins/parameterizedtrigger/FileBuildParameterFactory/help-noFilesFoundAction.html
- src/main/resources/hudson/plugins/parameterizedtrigger/SubversionRevisionBuildParameters/config.jelly
Link to the Jenkins instructions for managing system properties.
Use consistent headings and improve the phrasing a little.
Will confirm the page renders reasonably in GitHub.
```[tasklist]
```
> Remove System V init instructions that no longer work
